// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jyppxlopcvcwrlmrsoan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5cHB4bG9wY3Zjd3JsbXJzb2FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwOTQzNzMsImV4cCI6MjA1NjY3MDM3M30.4tkr_79mOojlbF4WtX8KEgATQ-ftJMW5plYgMDVYmpI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);